#!/bin/bash
# Script for releasing clautod
# Given a version number, this script creates a debian package
# from the clautod source, adds it to the local repo, and tags
# the current git commit with the same version number. This is
# the clautod release flow.
# The script is almost certainly broken on all machines except
# my home PC where it's intended to be run. Don't try it!

# Check parameters
if [ ! $1 ] ; then
    echo "Specify version string in X.X.X format"
    exit 1
fi
if [[ ! $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ; then
    echo "Version string <"$1"> is invalid"
    exit 1
fi

# Populate clautod-version.txt for setup.py to read
echo " # Do not edit this file! It's generated and used by a script
 # to pass version numbers to setup.py" > clautod-version.txt
echo $1 >> clautod-version.txt

echo "Packaging clautod v"$1

# Populate README files in debian directory
cp README.md debian/README.debian
cp README.md debian/README.source

# Populate changelog based on git log
echo "clautod ("$1") unstable; urgency=medium"                           > debian/changelog
echo ""                                                                 >> debian/changelog
git log --oneline $(git tag | sort -V | tail -n 1)..@ | sed 's/^/  * /' >> debian/changelog
echo ""                                                                 >> debian/changelog
echo " -- Jeremy Lerner <jeremy.cpsc.questions@gmail.com>  "$(date -R)  >> debian/changelog

# Let the user edit the changelist
nano debian/changelog

# Build the Debian package
if dpkg-buildpackage -us -uc ; then
	echo "Failed to build Debian package"
fi

# Tag the current commit in git
echo "Tagging current commit as v"$1
if git tag -a v$1 && git push --tags ; then
    echo "Successfully tagged commit"
else
    echo "Failed to tag commit. This is not a legitimate release!"
    exit 1
fi

# Add the new package to the local repo
sudo reprepro -b /var/www/repos/apt/debian includedeb stretch clautod_$1_all.deb

# Cleanup
rm clautod-version.txt
rm ../clautod_$1_all.deb
rm ../clautod_$1_amd64.buildinfo
rm ../clautod_$1_amd64.changes
rm ../clautod_$1.dsc
rm ../clautod_$1.tar.xz

echo "Cleaned up"
