import time

from clauto_common.util.log import Log

mylog = Log("clautod", "/var/log/clauto")
mylog = Log()

while 1:
    time.sleep(5)
    mylog.level_set("CRT")
    mylog.critical("This message is critical <1> <2> <3>")
    mylog.config("This message is configgey <1> <2> <3>")
    mylog.error("This message is errorey <1> <2> <3>")
    mylog.warning("This message is a warning <1> <2> <3>")
    mylog.info("This message is informative <1> <2> <3>")
    mylog.debug("This message is debuggey <1> <2> <3>")
    mylog.verbose("This message is verbose <1> <2> <3>")

    mylog.level_set("CFG")
    mylog.critical("This message is critical <1> <2> <3>")
    mylog.config("This message is configgey <1> <2> <3>")
    mylog.error("This message is errorey <1> <2> <3>")
    mylog.warning("This message is a warning <1> <2> <3>")
    mylog.info("This message is informative <1> <2> <3>")
    mylog.debug("This message is debuggey <1> <2> <3>")
    mylog.verbose("This message is verbose <1> <2> <3>")

    mylog.level_set("ERR")
    mylog.critical("This message is critical <1> <2> <3>")
    mylog.config("This message is configgey <1> <2> <3>")
    mylog.error("This message is errorey <1> <2> <3>")
    mylog.warning("This message is a warning <1> <2> <3>")
    mylog.info("This message is informative <1> <2> <3>")
    mylog.debug("This message is debuggey <1> <2> <3>")
    mylog.verbose("This message is verbose <1> <2> <3>")

    mylog.level_set("WRN")
    mylog.critical("This message is critical <1> <2> <3>")
    mylog.config("This message is configgey <1> <2> <3>")
    mylog.error("This message is errorey <1> <2> <3>")
    mylog.warning("This message is a warning <1> <2> <3>")
    mylog.info("This message is informative <1> <2> <3>")
    mylog.debug("This message is debuggey <1> <2> <3>")
    mylog.verbose("This message is verbose <1> <2> <3>")

    mylog.level_set("INF")
    mylog.critical("This message is critical <1> <2> <3>")
    mylog.config("This message is configgey <1> <2> <3>")
    mylog.error("This message is errorey <1> <2> <3>")
    mylog.warning("This message is a warning <1> <2> <3>")
    mylog.info("This message is informative <1> <2> <3>")
    mylog.debug("This message is debuggey <1> <2> <3>")
    mylog.verbose("This message is verbose <1> <2> <3>")

    mylog.level_set("DBG")
    mylog.critical("This message is critical <1> <2> <3>")
    mylog.config("This message is configgey <1> <2> <3>")
    mylog.error("This message is errorey <1> <2> <3>")
    mylog.warning("This message is a warning <1> <2> <3>")
    mylog.info("This message is informative <1> <2> <3>")
    mylog.debug("This message is debuggey <1> <2> <3>")
    mylog.verbose("This message is verbose <1> <2> <3>")

    mylog.level_set("VRB")
    mylog.critical("This message is critical <1> <2> <3>")
    mylog.config("This message is configgey <1> <2> <3>")
    mylog.error("This message is errorey <1> <2> <3>")
    mylog.warning("This message is a warning <1> <2> <3>")
    mylog.info("This message is informative <1> <2> <3>")
    mylog.debug("This message is debuggey <1> <2> <3>")
    mylog.verbose("This message is verbose")
